"""Emulate the building blocks of a four-step (Bailey) NTT of size 2^12 = 64 x 64.

Target pipeline::

    pre-twist mult -> NTT64 #1 -> transpose -> inter-stage mult -> NTT64 #2 -> post-twist

with **no modular reduction between stages** — lazy reduction only, so every port
width is whatever bound propagation says it is.

This harness covers three of those blocks:

  1. **Pre-twist bank** — 64 constant multipliers, u24 unsigned input, constants
     psi^i from ``NewTwiddles.xlsx!PRETWIST``. Generated by
     ``scripts/build_bank.py``; this script consumes its ``output_bounds.json``.
  2. **NTT64 #1** — GS forward cyclic, driven at the bank's per-index output bounds.
  3. **NTT64 #2** — the *same* GS grid, driven at the bound produced by the
     inter-stage multiply (NTT64 #1's output times a 64-bit unsigned twiddle).
     The two NTT64s differ only in input width, which is exactly what makes them
     two distinct RTL blocks.

Both NTT64s use ``NewTwiddles.xlsx!NTT_TWIDDLES``, verified to be the n=64 GS
forward cyclic grid at base w64 = psi^2 = 2^39. That base is **not** necessarily
Sage's ``F.zeta(64)``, so every reference comparison passes ``primitiveRoot``
explicitly.

Deferred (not modelled here beyond their effect on widths): the inter-stage
multipliers themselves (general 64x64, not constant multipliers) and the
post-twist bank (``POSTTWIST`` is (1/64)*psi^-i, i.e. inverse-flavoured).

Default mode is emulate-only — bounds, a width report, and three verifications.
No RTL and no remote work unless asked.

Run::

    conda activate ntt-sage
    python runFourStep64.py                      # emulate + verify only
    python runFourStep64.py --emit-rtl --backend both
"""
from __future__ import annotations

import argparse
import json
import random
import subprocess
import sys
from math import log2
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
WORKBOOK     = PROJECT_ROOT / "NewTwiddles.xlsx"
WORK_DIR     = PROJECT_ROOT / "work"

BANK_SCENARIO = "fourstep64_pretwist"
BANK_DIR      = WORK_DIR / BANK_SCENARIO / "cmultbank"
BANK_BOUNDS   = BANK_DIR / "output_bounds.json"

SCENARIO = "fourstep64"
TOP_A    = "NTT64_A"        # fed by the pre-twist bank
TOP_B    = "NTT64_B"        # fed by the inter-stage multiply

N          = 64
Q          = 2**64 - 2**32 + 1
PSI        = 17870292113338400769   # primitive 128th root of unity, psi^64 = -1
W64        = pow(PSI, 2, Q)         # = 2**39 — the base of the workbook's grid
BANK_IN_W  = 24                     # pre-twist bank input width (unsigned)
INTER_W    = 64                     # inter-stage twiddles are 64-bit unsigned
TEST_SIZE  = 1000
SEED       = 0
PIPELINE   = 1                      # broadcast to every layer


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_bank(IntType) -> tuple[list, list[int]]:
    """Return (per-index output bounds, per-index lifted constants) of the
    pre-twist bank. The constants are what the RTL actually multiplies by —
    congruent to psi^i mod q but not equal to it, since the generator
    NAF-lifts them."""
    from operator_modeling.core.IntType import loadBoundsJson

    if not BANK_BOUNDS.is_file():
        raise SystemExit(
            f"missing {BANK_BOUNDS}. Generate the pre-twist bank first:\n"
            f"  python scripts/build_bank.py --scenario {BANK_SCENARIO} \\\n"
            f"      --xlsx NewTwiddles.xlsx --sheet PRETWIST \\\n"
            f"      --width-a {BANK_IN_W} --modulus {Q} --pipeline-stages 1"
        )
    bounds = loadBoundsJson(str(BANK_BOUNDS))
    constants = [e["constant"] for e in json.loads(BANK_BOUNDS.read_text())]
    if len(bounds) != N or len(constants) != N:
        raise SystemExit(
            f"expected {N} bank entries, got {len(bounds)} bounds / "
            f"{len(constants)} constants from {BANK_BOUNDS}"
        )
    bad = [i for i, c in enumerate(constants) if c % Q != pow(PSI, i, Q)]
    if bad:
        raise SystemExit(
            f"bank constants are not congruent to psi^i mod q at indices "
            f"{bad[:8]}{'...' if len(bad) > 8 else ''} — wrong sheet or wrong psi?"
        )
    return bounds, constants


def build_instance(name: str, twiddles, bounds: list,
                   butterflyType: str = 'GS', inverse: bool = False):
    """Construct + bound-populate a cyclic NTT64/INTT64 at the given
    per-natural-index input bounds. Returns (instance, natural-order output
    bounds).

    Defaults to the forward GS pipeline used by this harness;
    ``runFourStep64Inverse.py`` reuses it with butterflyType='CT',
    inverse=True for the four-step's inverse half."""
    from operator_modeling.ntt.ButterflyScheme import GoldilocksSlice64
    from operator_modeling.ntt.NTT import FullyPipelinedNTT, FullyPipelinedINTT

    L = int(log2(N))
    klass = FullyPipelinedINTT if inverse else FullyPipelinedNTT
    inst = klass(name=name, n=N, q=Q, butterflyType=butterflyType,
                 twiddles=twiddles, negacyclic=False)
    inst.setScheme([[GoldilocksSlice64(name=f'{name}_L{s}_p{p}',
                                       butterflyType=butterflyType)
                     for p in range(N // 2)] for s in range(L)])
    inst.getInputsNatural(bounds)
    inst.compute()
    # getOutputs prefers `bound` over `testVector`, and only bounds are loaded
    # at this point, so this returns natural-order IntType bounds.
    return inst, inst.getOutputsNatural()


def width_span(bounds: list) -> str:
    widths = sorted({b.bitWidth for b in bounds})
    signed = {b.isSigned for b in bounds}
    sign = "signed" if signed == {True} else "unsigned" if signed == {False} else "mixed"
    if len(widths) == 1:
        return f"{widths[0]} bits ({sign})"
    return f"{widths[0]}..{widths[-1]} bits, {len(widths)} distinct ({sign})"


def interstage_bound(IntType, outA: list):
    """Bound after multiplying NTT64 #1's output by a 64-bit unsigned twiddle.
    Covers every natural index, so NTT64 #2 can be driven from one uniform
    bound the way the real hardware is."""
    products = [b * IntType.unsigned(INTER_W) for b in outA]
    lo = min(p.minValue for p in products)
    hi = max(p.maxValue for p in products)
    return IntType(lo, hi)


# ---------------------------------------------------------------------------
# Verification
# ---------------------------------------------------------------------------

def verify_composed_negacyclic(inst, bounds: list, constants: list[int],
                               batch_size: int = 8) -> bool:
    """Pre-twist by psi^i followed by a cyclic NTT *is* the negacyclic NTT:

        sum_i (x[i] * psi^i) * w^(i*k) = sum_i x[i] * psi^(i*(2k+1))

    So drive the bank's actual products through NTT64 #1 and compare against
    referenceNtt(..., negacyclic=True). This exercises the bank constants, the
    workbook twiddle grid, and the pipeline wiring in one check — something
    neither block's standalone test covers.
    """
    from operator_modeling.ntt.NTT import referenceNtt

    random.seed(SEED)
    xs = [[random.randint(0, (1 << BANK_IN_W) - 1) for _ in range(batch_size)]
          for _ in range(N)]
    twisted = [[v * constants[i] for v in xs[i]] for i in range(N)]

    inst.getInputsNatural(bounds)
    inst.getInputsNatural(twisted)
    inst.compute()
    _, goldenY = inst._extractGoldensNatural()   # [batch][natural index]

    fails = 0
    for b in range(batch_size):
        x = [xs[i][b] for i in range(N)]
        ref = referenceNtt(x, Q, primitiveRoot=PSI, negacyclic=True)
        for i in range(N):
            if goldenY[b][i] % Q != ref[i]:
                fails += 1
                if fails <= 5:
                    print(f'    mismatch batch {b} index {i}: '
                          f'got {goldenY[b][i] % Q}, ref {ref[i]}')
    total = batch_size * N
    print(f'  composed bank+NTT64_A vs negacyclic reference: '
          f'{total - fails}/{total}')
    return fails == 0


# ---------------------------------------------------------------------------
# RTL emission
# ---------------------------------------------------------------------------

def emit(inst, top: str, bounds: list, backend: str, run_dir: Path) -> dict:
    """Emit one NTT64's RTL. Re-drives bounds + values first: emitRtl's inline
    sanity check shortens every port's testVector to sanity_check_size, so a
    second emit would otherwise write fewer lines than TEST_SIZE."""
    random.seed(SEED)
    batches = [[random.randint(b.minValue, b.maxValue) for _ in range(TEST_SIZE)]
               for b in bounds]
    inst.getInputsNatural(bounds)
    inst.getInputsNatural(batches)
    inst.compute()

    print(f'[fourstep64] emitting {backend} RTL for {top} -> {run_dir}')
    manifest = inst.emitRtl(topName=top, run_dir=run_dir,
                            pipeline_stages_per_layer=PIPELINE,
                            gen_testbench=True, backend=backend)
    print(f"[fourstep64]   layer_latency={manifest['layer_latency']}, "
          f"total_latency={manifest['total_latency']}")

    spec = inst.getOperatorInterface(name=top)
    (run_dir / 'spec.json').write_text(json.dumps(spec.to_dict(), indent=2) + '\n')
    return manifest


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--emit-rtl", action="store_true",
                   help="also generate RTL for both NTT64s (default: emulate only)")
    p.add_argument("--backend", default="sim", choices=("hw", "sim", "both"),
                   help="RTL backend when --emit-rtl is set (default: sim)")
    p.add_argument("--batch-size", type=int, default=8,
                   help="batches per verification pass (default: 8)")
    p.add_argument("--save-bounds", action="store_true",
                   help="write per-port bounds to work/fourstep64/NTT64_bounds.xlsx")
    args = p.parse_args()

    sys.path.insert(0, str(PROJECT_ROOT))
    from operator_modeling.core.IntType import IntType
    from operator_modeling.ntt.NTT import loadTwiddlesFromXlsx, verifyNtt

    print("=" * 78)
    print(f"four-step NTT4096 building blocks — n={N}, q={Q}")
    print(f"  psi = {PSI} (primitive 128th root, psi^64 = -1)")
    print(f"  w64 = psi^2 = {W64} = 2^{W64.bit_length() - 1}")
    print("=" * 78)

    # ---- Block 1: pre-twist bank -----------------------------------------
    bankBounds, bankConstants = load_bank(IntType)
    print(f"\n[1] pre-twist bank: {N} cmults, in u{BANK_IN_W}, "
          f"out {width_span(bankBounds)}")
    print(f"    constants verified congruent to psi^i mod q")

    # ---- Twiddles ---------------------------------------------------------
    if not WORKBOOK.is_file():
        raise SystemExit(f"missing workbook: {WORKBOOK}")
    twiddles = loadTwiddlesFromXlsx(str(WORKBOOK), sheetName='NTT_TWIDDLES')
    L = int(log2(N))
    if len(twiddles) != L or any(len(layer) != N // 2 for layer in twiddles):
        raise SystemExit(
            f"NTT_TWIDDLES is {len(twiddles)} x {len(twiddles[0]) if twiddles else 0}, "
            f"expected {L} x {N // 2} for n={N}"
        )
    print(f"\n    twiddles: {WORKBOOK.name}!NTT_TWIDDLES, {L} layers x {N // 2}")

    # ---- Block 2: NTT64 #1 ------------------------------------------------
    instA, outA = build_instance(TOP_A, twiddles, bankBounds)
    print(f"\n[2] {TOP_A} (GS forward cyclic): in {width_span(bankBounds)} -> "
          f"out {width_span(outA)}")
    instA.showBounds()

    # ---- Inter-stage multiply (bound only) --------------------------------
    interBound = interstage_bound(IntType, outA)
    print(f"\n[3] inter-stage multiply: out(NTT64_A) x u{INTER_W} -> "
          f"{interBound.bitWidth} bits "
          f"({'signed' if interBound.isSigned else 'unsigned'})")
    print(f"    {interBound}")
    if interBound.bitWidth != 130:
        print(f"    NOTE: derived width {interBound.bitWidth} != the 130 expected "
              f"from the n=128 precedent — using the derived value.")

    # ---- Block 3: NTT64 #2 ------------------------------------------------
    boundsB = [interBound] * N
    instB, outB = build_instance(TOP_B, twiddles, boundsB)
    print(f"\n[4] {TOP_B} (GS forward cyclic): in {width_span(boundsB)} -> "
          f"out {width_span(outB)}")
    instB.showBounds()

    # ---- Verification -----------------------------------------------------
    print("\n" + "=" * 78)
    print("verification (Sage references)")
    print("=" * 78)

    print(f"\n  [a] {TOP_A} standalone, cyclic, primitiveRoot=w64")
    okA = verifyNtt(instA, primitiveRoot=W64, inputBound=bankBounds,
                    batchSize=args.batch_size, seed=SEED, verbose=True)

    print(f"\n  [b] bank + {TOP_A} composed == negacyclic NTT64")
    okC = verify_composed_negacyclic(instA, bankBounds, bankConstants,
                                     batch_size=args.batch_size)

    print(f"\n  [c] {TOP_B} standalone, cyclic, primitiveRoot=w64")
    okB = verifyNtt(instB, primitiveRoot=W64, inputBound=boundsB,
                    batchSize=args.batch_size, seed=SEED, verbose=True)

    # ---- Width report -----------------------------------------------------
    print("\n" + "=" * 78)
    print("width report")
    print("=" * 78)
    rows = [
        ("pre-twist bank",   f"u{BANK_IN_W}",          width_span(bankBounds)),
        (f"{TOP_A} (NTT64)", width_span(bankBounds),   width_span(outA)),
        ("inter-stage mult", width_span(outA) + f" x u{INTER_W}",
                             f"{interBound.bitWidth} bits (signed)"),
        (f"{TOP_B} (NTT64)", width_span(boundsB),      width_span(outB)),
    ]
    w0 = max(len(r[0]) for r in rows)
    w1 = max(len(r[1]) for r in rows)
    print(f"  {'block'.ljust(w0)}  {'in'.ljust(w1)}  out")
    print(f"  {'-' * w0}  {'-' * w1}  {'-' * 34}")
    for name, i, o in rows:
        print(f"  {name.ljust(w0)}  {i.ljust(w1)}  {o}")

    if args.save_bounds:
        out_xlsx = WORK_DIR / SCENARIO / "NTT64_bounds.xlsx"
        out_xlsx.parent.mkdir(parents=True, exist_ok=True)
        instA.saveBoundsToXlsx(path=str(out_xlsx), sheetName=TOP_A)
        instB.saveBoundsToXlsx(path=str(out_xlsx), sheetName=TOP_B)
        print(f"\n  bounds written to {out_xlsx}")

    if not (okA and okB and okC):
        print("\nVERIFICATION FAILED — not emitting RTL")
        return 1
    print("\nall three verifications passed")

    # ---- Optional RTL -----------------------------------------------------
    if args.emit_rtl:
        backends = ["hw", "sim"] if args.backend == "both" else [args.backend]
        for inst, top, bounds in ((instA, TOP_A, bankBounds),
                                  (instB, TOP_B, boundsB)):
            for backend in backends:
                target = top if backend == "hw" else f"{top}_sim"
                run_dir = WORK_DIR / SCENARIO / target
                emit(inst, target, bounds, backend, run_dir)
    return 0


if __name__ == "__main__":
    sys.exit(main())
