# rtl/emit_scoped_xdc.py
"""Scan the generated-output directory, pair up <name>.xdc with <name>.sv,
   read the real module name out of the .sv to use as the ref, and emit a
   scoped-constraints tcl script."""
from __future__ import annotations
import re
from pathlib import Path

_MODULE_RE = re.compile(r"^\s*module\s+([A-Za-z_]\w*)", re.M)


def _ref_of(sv: Path) -> str:
    """Pull the first module name out of the .sv -- never guessed from the filename."""
    m = _MODULE_RE.search(sv.read_text(encoding="utf-8"))
    if m is None:
        raise ValueError(f"{sv}: no module declaration found")
    return m.group(1)


def collect_scopes(outdir: str | Path,
                   patterns: tuple[str, ...] = ("*_bitheap_gen.xdc",
                                                "*_bitheap_cmp.xdc"),
                   ) -> list[tuple[Path, str]]:
    """Returns [(absolute xdc path, ref module name), ...]. Results across
    multiple patterns are deduplicated."""
    out = Path(outdir).resolve()
    seen: set[Path] = set()
    pairs: list[tuple[Path, str]] = []
    for pat in patterns:
        for xdc in sorted(out.rglob(pat)):
            if xdc in seen:
                continue
            seen.add(xdc)
            sv = next(out.rglob(f"{xdc.stem}.sv"), None)
            if sv is None:
                raise FileNotFoundError(f"{xdc.name}: no matching .sv found, can't determine the ref")
            pairs.append((xdc, _ref_of(sv)))
    return sorted(pairs, key=lambda p: p[0].name)


def write_scoped_xdc_tcl(outdir: str | Path, *,
                         mode: str = "project",
                        patterns: tuple[str, ...] = ("*_bitheap_gen.xdc",
                                                      "*_bitheap_cmp.xdc"),
                         tcl_name: str | None = None) -> Path:
    """mode='project' -> a set_property version with no path dependency
       (GUI project, no edits needed after moving to another server)
       mode='batch'   -> a read_xdc -ref version (a non-project script,
       must be placed after synth_design)"""
    out = Path(outdir).resolve()
    pairs = collect_scopes(out, patterns)         # still run this: validates the xdc/sv pairing
    if not pairs:
        # no compressor tree -> no GPC placement constraints -> no scoped tcl needed.
        # Don't write an empty file: a comment-only tcl left behind would
        # look like constraints had already been applied.
        print(f"No xdc matching {patterns}, skipping scoped tcl generation. ")
        return None


    tcl = out / (tcl_name or f"scoped_xdc_{mode}.tcl")

    header = [
        f"# Generated by EmitScopedXdc. Found {len(pairs)} xdc file(s) at generation time:",
        *[f"#   {x.name}  ->  {r}" for x, r in pairs],
        "",
    ]

    if mode == "project":
        body = [
            "# Usage: source this in Vivado GUI's Tcl Console.",
            "#   source once before synthesis -> attaches the properties",
            "#   source again after open_run synth_1 -> validates the ref",
            "# This script matches purely by filename, contains no absolute",
            "# paths, and can be used as-is after moving to another server.",
            "",
            f"set pats {{{' '.join(patterns)}}}",
            "set xdcs {}",
            "foreach p $pats {",
            "    foreach f [get_files -quiet $p] {",
            "        if {[lsearch -exact $xdcs $f] < 0} { lappend xdcs $f }",
            "    }",
            "}",
            "if {[llength $xdcs] == 0} {",
            "    error \"no xdc in the project matches $pats, add_files first\"",
            "}",
            "",
            "foreach f $xdcs {",
            "    set ref [file rootname [file tail $f]]",
            "    set_property SCOPED_TO_REF          $ref  $f",
            "    set_property SCOPED_TO_CELLS        {}    $f",
            "    set_property USED_IN_SYNTHESIS      false $f",
            "    set_property USED_IN_IMPLEMENTATION true  $f",
            "    puts \"scoped: [file tail $f] -> $ref\"",
            "}",
            "",
            "if {[current_design -quiet] eq \"\"} {",
            "    puts \"\\n(no design open, skipping ref validation; source again after open_run synth_1)\"",
            "} else {",
            "    puts \"\"",
            "    foreach f $xdcs {",
            "        set ref [get_property SCOPED_TO_REF $f]",
            "        set n   [llength [get_cells -quiet -hier -filter \"REF_NAME == $ref\"]]",
            "        if {$n == 0} {",
            "            puts \"WARNING: no REF_NAME == $ref in the netlist, this constraint won't take effect\"",
            "        } else {",
            "            puts \"OK: $ref  ($n instance(s))\"",
            "        }",
            "    }",
            "}",
        ]
    elif mode == "batch":
        body = [
            "# This script matches purely by filename, contains no absolute",
            "# paths, and can be used as-is after moving to another server.",
            "#   *_bitheap_gen.xdc -> LUT packing for the partial-product generation layer",
            "#   *_bitheap_cmp.xdc -> LUT packing for the compressor tree (GPC) layer",
            "set here [file dirname [file normalize [info script]]]",
        ]
        for xdc, ref in pairs:
            rel = xdc.relative_to(out).as_posix()
            body.append(f"read_xdc -ref {ref} [file join $here {rel}]")
    else:
        raise ValueError(f"unknown mode {mode!r}")

    tcl.write_text("\n".join(header + body) + "\n", encoding="utf-8")
    return tcl
