#!/usr/bin/env python3
"""clean_work.py — prune the per-scenario tree under ``work/`` down to a chosen
set of "keepers", and drop regenerable artifacts inside those.

Two operations, applied per-scenario in ``work/``:

1. **Scenarios NOT in ``--keep``** are deleted entirely.
2. **Scenarios in ``--keep``** are walked recursively; in every leaf run dir
   (one containing ``RTL_generated/``), regenerable artifacts are removed:

   - ``sim_remote/``                  (Vivado xsim build dir, ~GB; regenerated by run_remote_sim.py)
   - ``bitheap_visualization/``       (PNGs; regenerated by --visualization)
   - top-level ``*_bitheap.txt``      (per-compressor column heights; intermediate)

   What stays in each leaf run dir: ``RTL_generated/``, ``xdc_generated/``,
   ``testvectors/``, ``manifest.json``, ``spec.json`` (and the
   ``butterflies/`` subtree if it exists, with the same per-leaf pruning
   applied recursively).

Default mode is ``--dry-run`` (prints intent, touches nothing). Pass
``--apply`` to actually delete. Reports the size that will be / has been
freed.

Examples::

    # Dry-run: show what would happen, keep all four full-NTT pipelines.
    python scripts/clean_work.py \\
        --keep v80_ntt128_GS v80_ntt128_CT v80_intt128_GS v80_intt128_CT

    # Same, but actually do the work.
    python scripts/clean_work.py \\
        --keep v80_ntt128_GS v80_ntt128_CT v80_intt128_GS v80_intt128_CT \\
        --apply

    # Keep nothing — wipe the entire work/ tree.
    python scripts/clean_work.py --apply
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_WORK_DIR = PROJECT_ROOT / "work"

# Subdir names dropped inside every kept leaf run dir.
DROP_SUBDIRS = ("sim_remote", "bitheap_visualization")
# Glob patterns dropped at the top level of every kept leaf run dir.
DROP_FILE_GLOBS = ("*_bitheap.txt",)


def _dir_size_bytes(path: Path) -> int:
    """Recursive byte size; missing path returns 0."""
    if not path.exists():
        return 0
    if path.is_file() or path.is_symlink():
        try:
            return path.stat().st_size
        except OSError:
            return 0
    total = 0
    for sub in path.rglob("*"):
        try:
            if sub.is_file() and not sub.is_symlink():
                total += sub.stat().st_size
        except OSError:
            continue
    return total


def _format_size(n_bytes: int) -> str:
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if n_bytes < 1024 or unit == "TB":
            return f"{n_bytes:.1f} {unit}"
        n_bytes /= 1024
    return f"{n_bytes:.1f} TB"


def _is_leaf_run_dir(path: Path) -> bool:
    """A leaf run dir is one with an RTL_generated/ subdirectory directly inside."""
    return (path / "RTL_generated").is_dir()


def _iter_leaf_run_dirs(scenario_dir: Path):
    """Yield every leaf run dir under a scenario (a scenario can contain
    multiple, e.g. one full-NTT run dir + a `butterflies/` tree)."""
    if _is_leaf_run_dir(scenario_dir):
        yield scenario_dir
        return
    for sub in scenario_dir.rglob("RTL_generated"):
        if sub.is_dir():
            yield sub.parent


def _plan_prune_inside(leaf: Path) -> list[Path]:
    """Return the list of paths that would be removed inside one leaf run dir."""
    targets: list[Path] = []
    for name in DROP_SUBDIRS:
        d = leaf / name
        if d.exists():
            targets.append(d)
    for pattern in DROP_FILE_GLOBS:
        for f in leaf.glob(pattern):
            if f.is_file():
                targets.append(f)
    return targets


def main() -> int:
    p = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=__doc__,
    )
    p.add_argument(
        "--work-dir", default=str(DEFAULT_WORK_DIR),
        help=f"path to the work/ tree (default: {DEFAULT_WORK_DIR})",
    )
    p.add_argument(
        "--keep", nargs="*", default=[],
        help="scenario directory names to retain (matched literally against immediate "
             "children of <work-dir>). Scenarios not listed here are deleted entirely. "
             "If omitted, every scenario is deleted.",
    )
    p.add_argument(
        "--apply", action="store_true",
        help="actually delete. Without this flag the script runs in dry-run mode "
             "and only prints what would happen.",
    )
    args = p.parse_args()

    work_dir = Path(args.work_dir).resolve()
    if not work_dir.is_dir():
        print(f"[clean_work] {work_dir} does not exist or is not a directory", file=sys.stderr)
        return 2

    keep = set(args.keep)
    scenarios = sorted([d for d in work_dir.iterdir() if d.is_dir()])
    if not scenarios:
        print(f"[clean_work] no scenarios under {work_dir}; nothing to do")
        return 0

    delete_scenarios: list[Path] = []
    leaf_prunes: list[tuple[Path, list[Path]]] = []  # (leaf, targets)

    for scenario in scenarios:
        if scenario.name not in keep:
            delete_scenarios.append(scenario)
        else:
            for leaf in _iter_leaf_run_dirs(scenario):
                targets = _plan_prune_inside(leaf)
                if targets:
                    leaf_prunes.append((leaf, targets))

    bytes_to_free = sum(_dir_size_bytes(p) for p in delete_scenarios)
    for _, targets in leaf_prunes:
        bytes_to_free += sum(_dir_size_bytes(t) for t in targets)

    print(f"[clean_work] work-dir: {work_dir}")
    print(f"[clean_work] keep: {sorted(keep) if keep else '(none — wipe everything)'}")
    print(f"[clean_work] mode: {'APPLY (will delete)' if args.apply else 'dry-run (no changes)'}")
    print()

    if delete_scenarios:
        print(f"[clean_work] {len(delete_scenarios)} scenario(s) to delete entirely:")
        for s in delete_scenarios:
            sz = _dir_size_bytes(s)
            print(f"    rm -rf {s}    ({_format_size(sz)})")
        print()
    else:
        print("[clean_work] no scenarios to delete entirely.")
        print()

    if leaf_prunes:
        print(f"[clean_work] {len(leaf_prunes)} kept run dir(s) with regenerable artifacts to prune:")
        for leaf, targets in leaf_prunes:
            rel = leaf.relative_to(work_dir)
            inside_total = sum(_dir_size_bytes(t) for t in targets)
            print(f"  {rel}    ({_format_size(inside_total)} to free)")
            for t in targets:
                kind = "dir" if t.is_dir() else "file"
                print(f"      rm -rf [{kind}] {t.relative_to(leaf)}")
        print()
    else:
        print("[clean_work] no kept run dirs had regenerable artifacts to prune.")
        print()

    print(f"[clean_work] total to free: {_format_size(bytes_to_free)}")

    if not args.apply:
        print("[clean_work] dry-run — pass --apply to actually delete.")
        return 0

    # APPLY MODE — destructive.
    for scenario in delete_scenarios:
        print(f"[clean_work] rm -rf {scenario}")
        shutil.rmtree(scenario, ignore_errors=False)

    for leaf, targets in leaf_prunes:
        for t in targets:
            print(f"[clean_work] rm -rf {t}")
            if t.is_dir():
                shutil.rmtree(t, ignore_errors=False)
            else:
                t.unlink(missing_ok=True)

    # Final size readout.
    print()
    final_size = _dir_size_bytes(work_dir)
    print(f"[clean_work] done. work/ now occupies {_format_size(final_size)}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
