#!/usr/bin/env python3
"""run_remote_synth.py — stage a versal_arith run onto the V80 server and
run Vivado out-of-context (OOC) synthesis on it.

Workflow (mirrors run_remote_sim.py's structure):

  1. Validate the local run dir; auto-detect the top from
     ``RTL_generated/<top>_tb.sv`` (strip ``_tb``).
  2. Ensure GPC primitives are on the server (push if missing).
  3. Wipe ``src/rtl/`` (synth shares this slot with sim — sequential
     remote runs only, same convention as the sim flow).
  4. rsync ``RTL_generated/*.sv`` (excluding ``*_tb.sv``) into ``src/rtl/``.
  5. Generate a per-run synth driver tcl on local; push it to the server
     via ``ssh server 'cat > path'``. The tcl reads RTL from ``src/rtl/``
     + ``src/rtl_resources/``, applies ``tcl/const.tcl`` (the canonical
     5 ns clock), runs ``synth_design -mode out_of_context``, and writes
     the small ``utilization.rpt`` / ``timing_summary.rpt`` /
     ``timing_top10.rpt`` reports plus the multi-MB ``<top>_synth.dcp``
     checkpoint.
  6. Launch Vivado batch detached on the server (``setsid nohup``);
     the launching SSH returns within seconds.
  7. Poll an exit marker every 30 s (idle-timeout-resistant SSH calls).
  8. rsync the small reports + Vivado log back into ``<pull-to>/``;
     optionally pull the multi-MB ``<top>_synth.dcp`` (``--pull-dcp``).
  9. Parse ``utilization.rpt`` / ``timing_summary.rpt`` for a one-line
     summary (LUTs, FFs, WNS, TNS); print and exit 0/1/2.
 10. Optionally clean ``build_<top>_ooc/`` + tcl + log + marker on the
     server.

Run from the project root, e.g.::

    python scripts/run_remote_synth.py \\
        --run-dir work/ntt128_GS_after_pretwist/NTT_n128_GS_after_pretwist
"""

from __future__ import annotations

import argparse
import re
import shlex
import subprocess
import sys
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SCRIPTS_DIR = PROJECT_ROOT / "scripts"

# Reuse the small SSH/rsync helpers + detect_top + ensure_resources from the
# sim driver — same conventions, same defaults.
sys.path.insert(0, str(SCRIPTS_DIR))
from run_remote_sim import (  # noqa: E402
    DEFAULT_SERVER, DEFAULT_REMOTE_ROOT,
    EXIT_PASS, EXIT_FAIL, EXIT_TOOLING,
    _run, _ssh, detect_top, ensure_resources,
)


DEFAULT_PART = "xcv80-lsva4737-2MHP-e-S"  # AMD Alveo V80 board; override via --part for paper's xcvc1902.


# ---------------------------------------------------------------------------
# Server-side staging (synth-specific — only src/rtl/, no rtl_tb/testvectors)
# ---------------------------------------------------------------------------

def wipe_synth_slot(server: str, remote_root: str) -> None:
    """Clear the shared src/rtl/ slot. Doesn't touch src/rtl_tb/ or
    testvectors/ — those belong to the sim flow and are irrelevant for
    OOC synth."""
    cmd = (
        f"cd {shlex.quote(remote_root)} && "
        "rm -f src/rtl/*.sv src/rtl/*.v"
    )
    _ssh(server, cmd, check=True)


def stage_rtl(server: str, remote_root: str, run_dir: Path) -> None:
    """Push RTL_generated/*.sv (minus *_tb.sv) to src/rtl/. The TB is
    sim-only; OOC synth ignores it (and would fail to read it cleanly)."""
    _run([
        "rsync", "-a",
        "--include=*.sv", "--include=*.v",
        "--exclude=*_tb.sv", "--exclude=*_tb.v",
        "--exclude=*",
        f"{run_dir}/RTL_generated/",
        f"{server}:{remote_root}/src/rtl/",
    ], check=True)


# ---------------------------------------------------------------------------
# Per-run synth tcl generation + push
# ---------------------------------------------------------------------------

_GPC_PRIMITIVES = [
    # The 9 .sv files in versal_arith/rtl/. They live alongside ~hundreds of
    # Vivado primitive sim models in `src/rtl_resources/` on the server (e.g.
    # HPLL.v, DSP58.v, RAMB36E5.v); we explicitly list ours to avoid hauling
    # the sim-model library into synth_design (HPLL.v in particular has a
    # `$itor` system call that synthesis can't handle, and Vivado already
    # knows about every primitive we'd "find" via globbing).
    "c3_2.sv", "c6_3.sv", "c9_41.sv", "c15_3.sv",
    "c39_231.sv", "c223_4.sv", "c413_341.sv", "c517_451.sv",
    "LFSR.sv",
]


def build_synth_tcl(top: str, part: str, remote_root: str) -> str:
    """Per-run Vivado batch tcl. Self-contained: globs the staged RTL +
    explicitly lists the GPC primitives, applies the canonical clock from
    tcl/const.tcl, runs OOC synth, writes reports.

    The wipe-and-mkdir of build_<top>_ooc lives inside the tcl so a stale
    prior run can't pollute the result.
    """
    gpc_files = " ".join(
        f'"$origin_dir/src/rtl_resources/{name}"'
        for name in _GPC_PRIMITIVES
    )
    return f"""\
# auto-generated by scripts/run_remote_synth.py — do not edit
set top         "{top}"
set part        "{part}"
set origin_dir  "{remote_root}"

set ooc_dir "$origin_dir/build_${{top}}_ooc"
file delete -force $ooc_dir
file mkdir $ooc_dir
cd $ooc_dir

# RTL: the staged generated sources from src/rtl/ — globbed since the file
# list varies per run (different butterfly counts, etc.).
foreach f [glob -nocomplain "$origin_dir/src/rtl/*.sv" "$origin_dir/src/rtl/*.v"] {{
    if {{[string match "*.sv" $f]}} {{
        read_verilog -sv $f
    }} else {{
        read_verilog $f
    }}
}}

# GPC primitives: explicitly listed to avoid pulling in the dozens of
# Vivado primitive sim models that share src/rtl_resources/ (HPLL.v,
# DSP58.v, etc. — synthesis would either reject them or re-synthesize
# library cells unnecessarily).
foreach f [list {gpc_files}] {{
    read_verilog -sv $f
}}

# Canonical clock constraint from the server's tcl/ folder.
read_xdc "$origin_dir/tcl/const.tcl"

# Out-of-context synth with global retiming explicitly disabled. Vivado
# `synth_design -global_retiming auto` (the default) is "on" for Versal
# parts and "off" for others — i.e. for Versal/Alveo it actively retimes
# registers across combinational logic during synth. On large flat NTT
# pipelines that triggers a parallel-worker crash at Technology Mapping
# (multiple `hs_err_pid*.log` child-process aborts). `-global_retiming
# off` matches `versal_arith/docs/USAGE.md` §9's "disable automatic
# global retiming" recommendation.
synth_design -top $top -part $part -mode out_of_context -global_retiming off

write_checkpoint -force ${{top}}_synth.dcp
report_utilization -file utilization_synth.rpt

# `opt_design` is the standard post-synth logic-optimization pass —
# constant propagation, dead-code removal, equivalent-register merging,
# LUT combining. The post-opt netlist is much closer to what shows up
# after place-and-route, so utilization / timing numbers here are more
# realistic than the raw post-synth ones.
opt_design

write_checkpoint -force ${{top}}_opt.dcp
report_utilization     -file utilization.rpt
report_timing_summary  -file timing_summary.rpt
report_timing -nworst 10 -file timing_top10.rpt

puts "\\[synth_ooc\\] done"
exit
"""


def push_synth_tcl(server: str, remote_root: str, top: str, tcl_text: str) -> str:
    """Push the per-run tcl via ssh stdin. Returns the remote path."""
    dest = f"{remote_root}/build_{top}_ooc.tcl"
    print(f"[run_remote_synth] $ ssh {server} 'cat > {dest}'  (<{len(tcl_text)} bytes>)")
    subprocess.run(
        ["ssh", server, f"cat > {shlex.quote(dest)}"],
        input=tcl_text, text=True, check=True,
    )
    return dest


# ---------------------------------------------------------------------------
# Detached launch + poll for completion
# ---------------------------------------------------------------------------

def run_synth(server: str, remote_root: str, top: str, pull_to: Path,
              tcl_remote: str, poll_interval_s: int = 30) -> tuple[int, str]:
    """Launch Vivado batch detached, poll the exit marker, rsync the log.

    Returns (synth_exit_code, log_text). synth_exit_code is the Vivado
    process exit (0 = synth_design + reports completed; non-zero = failure).
    """
    log_remote = f"{remote_root}/build_{top}_ooc.log"
    exit_remote = f"{remote_root}/build_{top}_ooc.exit"
    log_local = pull_to / "synth_stdout.log"
    pull_to.mkdir(parents=True, exist_ok=True)

    # Detached launch — launching SSH returns within seconds; the actual
    # synth (5–60 min on Versal) runs in a session that survives any
    # network hiccup or local Ctrl-C.
    launch_cmd = (
        f"cd {shlex.quote(remote_root)} && "
        f"rm -f {shlex.quote(exit_remote)} && "
        f"setsid nohup bash -c "
        f"'cd {shlex.quote(remote_root)} && source ./source && "
        f"vivado -mode batch -source {shlex.quote(tcl_remote)} "
        f"> {shlex.quote(log_remote)} 2>&1; "
        f"echo $? > {shlex.quote(exit_remote)}' "
        f"</dev/null >/dev/null 2>&1 &"
    )
    print(f"[run_remote_synth] launching detached OOC synth on {server}")
    _ssh(server, launch_cmd, check=True)

    print(f"[run_remote_synth] polling for {exit_remote} every {poll_interval_s}s")
    synth_exit: int | None = None
    while synth_exit is None:
        time.sleep(poll_interval_s)
        proc = subprocess.run(
            ["ssh",
             "-o", "ServerAliveInterval=30", "-o", "ServerAliveCountMax=3",
             "-o", "ConnectTimeout=30",
             server,
             f"test -f {shlex.quote(exit_remote)} && cat {shlex.quote(exit_remote)} || echo NOT_DONE"],
            capture_output=True, text=True,
        )
        if proc.returncode != 0:
            print(f"[run_remote_synth] poll SSH failed (rc={proc.returncode}, "
                  f"stderr={proc.stderr.strip()!r}); retrying")
            continue
        out = proc.stdout.strip()
        if out == "NOT_DONE" or out == "":
            continue
        try:
            synth_exit = int(out)
        except ValueError:
            print(f"[run_remote_synth] unexpected exit marker: {out!r}; retrying")
            continue
    print(f"[run_remote_synth] synth done, exit={synth_exit}; pulling log + reports")

    try:
        _run([
            "rsync", "-a",
            f"{server}:{log_remote}",
            str(log_local),
        ], check=True)
    except subprocess.CalledProcessError as e:
        print(f"[run_remote_synth] warning: rsync of synth log failed ({e})")
        log_local.write_text("")

    log_text = log_local.read_text() if log_local.exists() else ""
    return synth_exit, log_text


# ---------------------------------------------------------------------------
# Pull reports back
# ---------------------------------------------------------------------------

def pull_reports(server: str, remote_root: str, top: str, pull_to: Path,
                 pull_dcp: bool = False) -> None:
    """Pull the small text reports back. DCPs (multi-MB) are opt-in.

    Reports pulled by default:
      - utilization_synth.rpt — raw post-synth (pre-opt) utilization.
      - utilization.rpt        — post-`opt_design` utilization (more realistic).
      - timing_summary.rpt     — post-opt WNS / TNS / etc.
      - timing_top10.rpt       — post-opt 10 worst paths.

    With `--pull-dcp`:
      - <top>_synth.dcp — post-synth, pre-opt checkpoint.
      - <top>_opt.dcp   — post-opt checkpoint (best to open in Vivado GUI).
    """
    pull_to.mkdir(parents=True, exist_ok=True)
    for rpt in ("utilization_synth.rpt", "utilization.rpt",
                "timing_summary.rpt", "timing_top10.rpt"):
        try:
            _run([
                "rsync", "-a",
                f"{server}:{remote_root}/build_{top}_ooc/{rpt}",
                f"{pull_to}/{rpt}",
            ], check=True)
        except subprocess.CalledProcessError as e:
            print(f"[run_remote_synth] note: {rpt} not pulled "
                  f"(rc={e.returncode}); synth may have failed before report stage.")
    if pull_dcp:
        for dcp in (f"{top}_synth.dcp", f"{top}_opt.dcp"):
            try:
                _run([
                    "rsync", "-a",
                    f"{server}:{remote_root}/build_{top}_ooc/{dcp}",
                    f"{pull_to}/{dcp}",
                ], check=True)
            except subprocess.CalledProcessError as e:
                print(f"[run_remote_synth] warning: {dcp} not pulled ({e}).")


# ---------------------------------------------------------------------------
# Parse reports for a one-line summary
# ---------------------------------------------------------------------------

# The Vivado utilization report's "Netlist Logic" section at the top is
# the authoritative summary — it accounts for Versal LUT-combining and
# pairs LUTCY1/LUTCY2 onto single CLB-LUT sites, so its numbers match
# what Vivado claims as the design's actual primitive footprint. The
# per-cell LUT1/LUT2/.../LUT6 rows further down only count the small
# combinational LUTs (a tiny fraction on Versal carry-heavy designs).
# Pattern: `| CLB LUTs* | <num> | ...` (the `*` after "CLB LUTs" is
# Vivado's footnote-marker, present on Versal/Alveo).
_CLB_LUTS_RE    = re.compile(r"^\|\s*CLB LUTs\*?\s*\|\s*(\d+)\s*\|",      re.MULTILINE)
_SLICE_LUTS_RE  = re.compile(r"^\|\s*Slice LUTs\*?\s*\|\s*(\d+)\s*\|",    re.MULTILINE)  # UltraScale+
_REGISTERS_RE   = re.compile(r"^\|\s*Registers\s*\|\s*(\d+)\s*\|",        re.MULTILINE)
_LOOKAHEAD8_RE  = re.compile(r"^\|\s*LOOKAHEAD8\s*\|\s*(\d+)\s*\|",       re.MULTILINE)
_WNS_RE         = re.compile(r"^\s*WNS\(ns\).*?\n\s*[-\s]+\n\s*(-?\d+\.?\d*)", re.MULTILINE)
_TNS_RE         = re.compile(r"^\s*TNS\(ns\).*?\n\s*[-\s]+\n.*?(-?\d+\.?\d*)", re.MULTILINE)


def parse_summary(pull_to: Path) -> str:
    util_path = pull_to / "utilization.rpt"     # post-opt — the headline numbers
    timing_path = pull_to / "timing_summary.rpt"
    parts: list[str] = []

    if util_path.is_file():
        util = util_path.read_text()
        m_lut = _CLB_LUTS_RE.search(util) or _SLICE_LUTS_RE.search(util)
        m_reg = _REGISTERS_RE.search(util)
        m_la  = _LOOKAHEAD8_RE.search(util)
        if m_lut:
            parts.append(f"LUTs={m_lut.group(1)}")
        if m_reg:
            parts.append(f"Regs={m_reg.group(1)}")
        if m_la:
            parts.append(f"LOOKAHEAD8={m_la.group(1)}")
    else:
        parts.append("(utilization.rpt missing)")

    if timing_path.is_file():
        timing = timing_path.read_text()
        m_wns = _WNS_RE.search(timing)
        m_tns = _TNS_RE.search(timing)
        if m_wns:
            parts.append(f"WNS={m_wns.group(1)}ns")
        if m_tns:
            parts.append(f"TNS={m_tns.group(1)}ns")

    return ", ".join(parts) if parts else "(no report fields parsed)"


# ---------------------------------------------------------------------------
# Cleanup remote
# ---------------------------------------------------------------------------

def cleanup_remote(server: str, remote_root: str, top: str) -> None:
    _ssh(server,
         f"rm -rf {shlex.quote(remote_root)}/build_{top}_ooc "
         f"{shlex.quote(remote_root)}/build_{top}_ooc.tcl "
         f"{shlex.quote(remote_root)}/build_{top}_ooc.log "
         f"{shlex.quote(remote_root)}/build_{top}_ooc.exit",
         check=True)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--run-dir", required=True,
                   help="path to a generated run dir (the dir containing "
                        "RTL_generated/), e.g. "
                        "work/ntt128_GS_after_pretwist/NTT_n128_GS_after_pretwist")
    p.add_argument("--top", default=None,
                   help="top module to synthesize (auto-detected from "
                        "RTL_generated/*_tb.sv if omitted)")
    p.add_argument("--part", default=DEFAULT_PART,
                   help=f"Vivado target part (default: {DEFAULT_PART})")
    p.add_argument("--server", default=DEFAULT_SERVER,
                   help=f"SSH alias of the V80 server (default: {DEFAULT_SERVER})")
    p.add_argument("--remote-root", default=DEFAULT_REMOTE_ROOT,
                   help=f"path to the Vivado project on the server "
                        f"(default: {DEFAULT_REMOTE_ROOT})")
    p.add_argument("--pull-to", default=None,
                   help="local directory for the pulled-back reports "
                        "(default: <run_dir>/synth_remote)")
    p.add_argument("--pull-dcp", action="store_true",
                   help="rsync the multi-MB <top>_synth.dcp checkpoint back "
                        "in addition to the small .rpt reports. Default off.")
    p.add_argument("--keep-remote-build", action="store_true",
                   help="don't `rm -rf build_<top>_ooc` on the server after pulling")
    p.add_argument("--no-prune-server", action="store_true",
                   help="skip wiping src/rtl/ before staging (use when the "
                        "staged sources are already correct from a previous run)")
    args = p.parse_args()

    run_dir = Path(args.run_dir).resolve()
    if not (run_dir / "RTL_generated").is_dir():
        raise SystemExit(f"missing {run_dir}/RTL_generated/")

    top = detect_top(run_dir, args.top)
    pull_to = Path(args.pull_to).resolve() if args.pull_to else run_dir / "synth_remote"
    print(f"[run_remote_synth] run_dir:    {run_dir}")
    print(f"[run_remote_synth] top:        {top}")
    print(f"[run_remote_synth] part:       {args.part}")
    print(f"[run_remote_synth] server:     {args.server}")
    print(f"[run_remote_synth] remote:     {args.remote_root}")
    print(f"[run_remote_synth] pull-to:    {pull_to}")

    try:
        ensure_resources(args.server, args.remote_root)
        if not args.no_prune_server:
            wipe_synth_slot(args.server, args.remote_root)
        stage_rtl(args.server, args.remote_root, run_dir)
        tcl_text = build_synth_tcl(top, args.part, args.remote_root)
        tcl_remote = push_synth_tcl(args.server, args.remote_root, top, tcl_text)
    except subprocess.CalledProcessError as e:
        print(f"[run_remote_synth] staging failed: {e}", file=sys.stderr)
        return EXIT_TOOLING

    synth_rc, _synth_log = run_synth(args.server, args.remote_root, top, pull_to, tcl_remote)

    try:
        pull_reports(args.server, args.remote_root, top, pull_to,
                     pull_dcp=args.pull_dcp)
    except subprocess.CalledProcessError as e:
        print(f"[run_remote_synth] pull-back failed: {e}", file=sys.stderr)
        return EXIT_TOOLING

    if synth_rc != 0:
        print(f"[run_remote_synth] {top}: synth FAILED — Vivado exit {synth_rc}, "
              f"see {pull_to}/synth_stdout.log", file=sys.stderr)
        return EXIT_FAIL

    summary = parse_summary(pull_to)
    print(f"[run_remote_synth] {top}: synth-OOC OK — {summary}")
    print(f"[run_remote_synth] reports in {pull_to}/")

    if not args.keep_remote_build:
        try:
            cleanup_remote(args.server, args.remote_root, top)
        except subprocess.CalledProcessError as e:
            print(f"[run_remote_synth] warning: cleanup failed: {e}", file=sys.stderr)

    return EXIT_PASS


if __name__ == "__main__":
    sys.exit(main())
